"""
Authoritative Pan-India District Registry (Local Government Directory & GoI Master).
Contains all current official districts across all 28 States and 8 Union Territories with official LGD/UDISE codes.
"""
from typing import Dict, List, Any, Tuple
from pathlib import Path
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment

# Authoritative State/UT definitions with Official Order & Codes
OFFICIAL_STATES = [
    # (Order, State/UT Name, Type, State Code, Sheet Name <= 31 chars)
    (1, "Andhra Pradesh", "State", "AP", "Andhra Pradesh"),
    (2, "Arunachal Pradesh", "State", "AR", "Arunachal Pradesh"),
    (3, "Assam", "State", "AS", "Assam"),
    (4, "Bihar", "State", "BR", "Bihar"),
    (5, "Chhattisgarh", "State", "CG", "Chhattisgarh"),
    (6, "Goa", "State", "GA", "Goa"),
    (7, "Gujarat", "State", "GJ", "Gujarat"),
    (8, "Haryana", "State", "HR", "Haryana"),
    (9, "Himachal Pradesh", "State", "HP", "Himachal Pradesh"),
    (10, "Jharkhand", "State", "JH", "Jharkhand"),
    (11, "Karnataka", "State", "KA", "Karnataka"),
    (12, "Kerala", "State", "KL", "Kerala"),
    (13, "Madhya Pradesh", "State", "MP", "Madhya Pradesh"),
    (14, "Maharashtra", "State", "MH", "Maharashtra"),
    (15, "Manipur", "State", "MN", "Manipur"),
    (16, "Meghalaya", "State", "ML", "Meghalaya"),
    (17, "Mizoram", "State", "MZ", "Mizoram"),
    (18, "Nagaland", "State", "NL", "Nagaland"),
    (19, "Odisha", "State", "OD", "Odisha"),
    (20, "Punjab", "State", "PB", "Punjab"),
    (21, "Rajasthan", "State", "RJ", "Rajasthan"),
    (22, "Sikkim", "State", "SK", "Sikkim"),
    (23, "Tamil Nadu", "State", "TN", "Tamil Nadu"),
    (24, "Telangana", "State", "TG", "Telangana"),
    (25, "Tripura", "State", "TR", "Tripura"),
    (26, "Uttar Pradesh", "State", "UP", "Uttar Pradesh"),
    (27, "Uttarakhand", "State", "UK", "Uttarakhand"),
    (28, "West Bengal", "State", "WB", "West Bengal"),
    (29, "Andaman and Nicobar Islands", "UT", "AN", "Andaman & Nicobar"),
    (30, "Chandigarh", "UT", "CH", "Chandigarh"),
    (31, "Dadra and Nagar Haveli and Daman and Diu", "UT", "DD", "DNH & Diu"),
    (32, "Delhi", "UT", "DL", "Delhi"),
    (33, "Jammu and Kashmir", "UT", "JK", "Jammu & Kashmir"),
    (34, "Ladakh", "UT", "LA", "Ladakh"),
    (35, "Lakshadweep", "UT", "LD", "Lakshadweep"),
    (36, "Puducherry", "UT", "PY", "Puducherry"),
]

# Complete authoritative district mapping for every single State and Union Territory
# (Based on Local Government Directory / Ministry of Panchayati Raj / UDISE+ Master)
LGD_DISTRICT_MASTER: Dict[str, List[Dict[str, str]]] = {
    "ANDHRA PRADESH": [
        {"name": "Alluri Sitharama Raju", "code": "AP-ASR", "lgd": "744"},
        {"name": "Anakapalli", "code": "AP-AKP", "lgd": "745"},
        {"name": "Ananthapuramu", "code": "AP-ATP", "lgd": "502"},
        {"name": "Annamayya", "code": "AP-ANN", "lgd": "746"},
        {"name": "Bapatla", "code": "AP-BPT", "lgd": "747"},
        {"name": "Chittoor", "code": "AP-CTR", "lgd": "503"},
        {"name": "Dr. B.R. Ambedkar Konaseema", "code": "AP-KNS", "lgd": "748"},
        {"name": "East Godavari", "code": "AP-EGD", "lgd": "505"},
        {"name": "Eluru", "code": "AP-ELR", "lgd": "749"},
        {"name": "Guntur", "code": "AP-GNT", "lgd": "506"},
        {"name": "Kakinada", "code": "AP-KKD", "lgd": "750"},
        {"name": "Krishna", "code": "AP-KRI", "lgd": "510"},
        {"name": "Kurnool", "code": "AP-KNL", "lgd": "511"},
        {"name": "Nandyal", "code": "AP-NDL", "lgd": "751"},
        {"name": "NTR", "code": "AP-NTR", "lgd": "752"},
        {"name": "Palnadu", "code": "AP-PLN", "lgd": "753"},
        {"name": "Parvathipuram Manyam", "code": "AP-PVM", "lgd": "754"},
        {"name": "Prakasam", "code": "AP-PRK", "lgd": "517"},
        {"name": "SPSR Nellore", "code": "AP-NLR", "lgd": "515"},
        {"name": "Sri Sathya Sai", "code": "AP-SSS", "lgd": "755"},
        {"name": "Srikakulam", "code": "AP-SKM", "lgd": "519"},
        {"name": "Tirupati", "code": "AP-TPT", "lgd": "756"},
        {"name": "Visakhapatnam", "code": "AP-VSP", "lgd": "520"},
        {"name": "Vizianagaram", "code": "AP-VZM", "lgd": "521"},
        {"name": "West Godavari", "code": "AP-WGD", "lgd": "523"},
        {"name": "YSR Kadapa", "code": "AP-KDP", "lgd": "504"},
    ],
    "ARUNACHAL PRADESH": [
        {"name": "Anjaw", "code": "AR-AJ", "lgd": "603"},
        {"name": "Changlang", "code": "AR-CH", "lgd": "230"},
        {"name": "Dibang Valley", "code": "AR-DV", "lgd": "231"},
        {"name": "East Kameng", "code": "AR-EK", "lgd": "232"},
        {"name": "East Siang", "code": "AR-ES", "lgd": "233"},
        {"name": "Kamle", "code": "AR-KM", "lgd": "718"},
        {"name": "Kra Daadi", "code": "AR-KD", "lgd": "673"},
        {"name": "Kurung Kumey", "code": "AR-KK", "lgd": "234"},
        {"name": "Lepa Rada", "code": "AR-LR", "lgd": "726"},
        {"name": "Lohit", "code": "AR-LH", "lgd": "235"},
        {"name": "Longding", "code": "AR-LD", "lgd": "658"},
        {"name": "Lower Dibang Valley", "code": "AR-LDV", "lgd": "236"},
        {"name": "Lower Siang", "code": "AR-LS", "lgd": "717"},
        {"name": "Lower Subansiri", "code": "AR-LSU", "lgd": "237"},
        {"name": "Namsai", "code": "AR-NM", "lgd": "674"},
        {"name": "Pakke Kessang", "code": "AR-PK", "lgd": "727"},
        {"name": "Papum Pare", "code": "AR-PP", "lgd": "238"},
        {"name": "Shi Yomi", "code": "AR-SY", "lgd": "728"},
        {"name": "Siang", "code": "AR-SG", "lgd": "675"},
        {"name": "Tawang", "code": "AR-TW", "lgd": "239"},
        {"name": "Tirap", "code": "AR-TI", "lgd": "240"},
        {"name": "Upper Siang", "code": "AR-US", "lgd": "241"},
        {"name": "Upper Subansiri", "code": "AR-USU", "lgd": "242"},
        {"name": "West Kameng", "code": "AR-WK", "lgd": "243"},
        {"name": "West Siang", "code": "AR-WS", "lgd": "244"},
        {"name": "Keyi Panyor", "code": "AR-KP", "lgd": "770"},
        {"name": "Bichom", "code": "AR-BC", "lgd": "771"},
    ],
    "ASSAM": [
        {"name": "Baksa", "code": "AS-BK", "lgd": "577"},
        {"name": "Barpeta", "code": "AS-BP", "lgd": "279"},
        {"name": "Biswanath", "code": "AS-BS", "lgd": "681"},
        {"name": "Bongaigaon", "code": "AS-BO", "lgd": "280"},
        {"name": "Cachar", "code": "AS-CA", "lgd": "281"},
        {"name": "Charaideo", "code": "AS-CD", "lgd": "682"},
        {"name": "Chirang", "code": "AS-CH", "lgd": "578"},
        {"name": "Darrang", "code": "AS-DA", "lgd": "282"},
        {"name": "Dhemaji", "code": "AS-DM", "lgd": "283"},
        {"name": "Dhubri", "code": "AS-DH", "lgd": "284"},
        {"name": "Dibrugarh", "code": "AS-DI", "lgd": "285"},
        {"name": "Dima Hasao", "code": "AS-NC", "lgd": "299"},
        {"name": "Goalpara", "code": "AS-GO", "lgd": "286"},
        {"name": "Golaghat", "code": "AS-GG", "lgd": "287"},
        {"name": "Hailakandi", "code": "AS-HA", "lgd": "288"},
        {"name": "Hojai", "code": "AS-HJ", "lgd": "683"},
        {"name": "Jorhat", "code": "AS-JO", "lgd": "289"},
        {"name": "Kamrup", "code": "AS-KR", "lgd": "290"},
        {"name": "Kamrup Metropolitan", "code": "AS-KM", "lgd": "579"},
        {"name": "Karbi Anglong", "code": "AS-KA", "lgd": "291"},
        {"name": "Karimganj", "code": "AS-KJ", "lgd": "292"},
        {"name": "Kokrajhar", "code": "AS-KO", "lgd": "293"},
        {"name": "Lakhimpur", "code": "AS-LA", "lgd": "294"},
        {"name": "Majuli", "code": "AS-MJ", "lgd": "688"},
        {"name": "Morigaon", "code": "AS-MA", "lgd": "295"},
        {"name": "Nagaon", "code": "AS-NG", "lgd": "296"},
        {"name": "Nalbari", "code": "AS-NL", "lgd": "297"},
        {"name": "Sivasagar", "code": "AS-SV", "lgd": "300"},
        {"name": "Sonitpur", "code": "AS-ST", "lgd": "301"},
        {"name": "South Salmara-Mankachar", "code": "AS-SS", "lgd": "684"},
        {"name": "Tamulpur", "code": "AS-TP", "lgd": "743"},
        {"name": "Tinsukia", "code": "AS-TI", "lgd": "302"},
        {"name": "Udalguri", "code": "AS-UD", "lgd": "580"},
        {"name": "West Karbi Anglong", "code": "AS-WK", "lgd": "685"},
        {"name": "Bajali", "code": "AS-BJ", "lgd": "737"},
    ],
    "BIHAR": [
        {"name": "Araria", "code": "BR-AR", "lgd": "188"},
        {"name": "Arwal", "code": "BR-AW", "lgd": "572"},
        {"name": "Aurangabad", "code": "BR-AU", "lgd": "189"},
        {"name": "Banka", "code": "BR-BA", "lgd": "190"},
        {"name": "Begusarai", "code": "BR-BE", "lgd": "191"},
        {"name": "Bhagalpur", "code": "BR-BG", "lgd": "192"},
        {"name": "Bhojpur", "code": "BR-BJ", "lgd": "193"},
        {"name": "Buxar", "code": "BR-BU", "lgd": "194"},
        {"name": "Darbhanga", "code": "BR-DA", "lgd": "195"},
        {"name": "East Champaran", "code": "BR-EC", "lgd": "213"},
        {"name": "Gaya", "code": "BR-GA", "lgd": "196"},
        {"name": "Gopalganj", "code": "BR-GO", "lgd": "197"},
        {"name": "Jamui", "code": "BR-JA", "lgd": "198"},
        {"name": "Jehanabad", "code": "BR-JE", "lgd": "199"},
        {"name": "Kaimur", "code": "BR-KM", "lgd": "200"},
        {"name": "Katihar", "code": "BR-KT", "lgd": "201"},
        {"name": "Khagaria", "code": "BR-KH", "lgd": "202"},
        {"name": "Kishanganj", "code": "BR-KI", "lgd": "203"},
        {"name": "Lakhisarai", "code": "BR-LA", "lgd": "204"},
        {"name": "Madhepura", "code": "BR-MP", "lgd": "205"},
        {"name": "Madhubani", "code": "BR-MB", "lgd": "206"},
        {"name": "Munger", "code": "BR-MG", "lgd": "207"},
        {"name": "Muzaffarpur", "code": "BR-MZ", "lgd": "208"},
        {"name": "Nalanda", "code": "BR-NL", "lgd": "209"},
        {"name": "Nawada", "code": "BR-NW", "lgd": "210"},
        {"name": "Patna", "code": "BR-PA", "lgd": "211"},
        {"name": "Purnia", "code": "BR-PU", "lgd": "212"},
        {"name": "Rohtas", "code": "BR-RO", "lgd": "214"},
        {"name": "Saharsa", "code": "BR-SH", "lgd": "215"},
        {"name": "Samastipur", "code": "BR-SM", "lgd": "216"},
        {"name": "Saran", "code": "BR-SR", "lgd": "217"},
        {"name": "Sheikhpura", "code": "BR-SK", "lgd": "218"},
        {"name": "Sheohar", "code": "BR-SO", "lgd": "219"},
        {"name": "Sitamarhi", "code": "BR-ST", "lgd": "220"},
        {"name": "Siwan", "code": "BR-SW", "lgd": "221"},
        {"name": "Supaul", "code": "BR-SP", "lgd": "222"},
        {"name": "Vaishali", "code": "BR-VA", "lgd": "223"},
        {"name": "West Champaran", "code": "BR-WC", "lgd": "224"},
    ],
    "CHHATTISGARH": [
        {"name": "Balod", "code": "CG-BL", "lgd": "646"},
        {"name": "Baloda Bazar", "code": "CG-BB", "lgd": "647"},
        {"name": "Balrampur", "code": "CG-BR", "lgd": "648"},
        {"name": "Bastar", "code": "CG-BA", "lgd": "374"},
        {"name": "Bemetara", "code": "CG-BM", "lgd": "649"},
        {"name": "Bijapur", "code": "CG-BP", "lgd": "607"},
        {"name": "Bilaspur", "code": "CG-BI", "lgd": "375"},
        {"name": "Dantewada", "code": "CG-DA", "lgd": "376"},
        {"name": "Dhamtari", "code": "CG-DH", "lgd": "377"},
        {"name": "Durg", "code": "CG-DU", "lgd": "378"},
        {"name": "Gariaband", "code": "CG-GB", "lgd": "650"},
        {"name": "Gaurela-Pendra-Marwahi", "code": "CG-GP", "lgd": "733"},
        {"name": "Janjgir-Champa", "code": "CG-JC", "lgd": "379"},
        {"name": "Jashpur", "code": "CG-JA", "lgd": "380"},
        {"name": "Kabirdham", "code": "CG-KB", "lgd": "381"},
        {"name": "Kanker", "code": "CG-KK", "lgd": "382"},
        {"name": "Khairagarh-Chhuikhadan-Gandai", "code": "CG-KC", "lgd": "758"},
        {"name": "Kondagaon", "code": "CG-KN", "lgd": "651"},
        {"name": "Korba", "code": "CG-KB", "lgd": "383"},
        {"name": "Korea", "code": "CG-KR", "lgd": "384"},
        {"name": "Mahasamund", "code": "CG-MA", "lgd": "385"},
        {"name": "Manendragarh-Chirmiri-Bharatpur", "code": "CG-MC", "lgd": "759"},
        {"name": "Mohla-Manpur-Ambagarh Chowki", "code": "CG-MM", "lgd": "760"},
        {"name": "Mungeli", "code": "CG-MG", "lgd": "652"},
        {"name": "Narayanpur", "code": "CG-NR", "lgd": "608"},
        {"name": "Raigarh", "code": "CG-RG", "lgd": "386"},
        {"name": "Raipur", "code": "CG-RP", "lgd": "387"},
        {"name": "Rajnandgaon", "code": "CG-RN", "lgd": "388"},
        {"name": "Sakti", "code": "CG-SK", "lgd": "761"},
        {"name": "Sarangarh-Bilaigarh", "code": "CG-SB", "lgd": "762"},
        {"name": "Sukma", "code": "CG-SKM", "lgd": "653"},
        {"name": "Surajpur", "code": "CG-SJ", "lgd": "654"},
        {"name": "Surguja", "code": "CG-SU", "lgd": "389"},
    ],
    "GOA": [
        {"name": "North Goa", "code": "GA-NG", "lgd": "544"},
        {"name": "South Goa", "code": "GA-SG", "lgd": "545"},
    ],
    "GUJARAT": [
        {"name": "Ahmedabad", "code": "GJ-AH", "lgd": "438"},
        {"name": "Amreli", "code": "GJ-AM", "lgd": "439"},
        {"name": "Anand", "code": "GJ-AN", "lgd": "440"},
        {"name": "Aravalli", "code": "GJ-AR", "lgd": "667"},
        {"name": "Banaskantha", "code": "GJ-BK", "lgd": "441"},
        {"name": "Bharuch", "code": "GJ-BR", "lgd": "442"},
        {"name": "Bhavnagar", "code": "GJ-BV", "lgd": "443"},
        {"name": "Botad", "code": "GJ-BT", "lgd": "668"},
        {"name": "Chhota Udaepur", "code": "GJ-CU", "lgd": "669"},
        {"name": "Dahod", "code": "GJ-DA", "lgd": "444"},
        {"name": "Dang", "code": "GJ-DG", "lgd": "445"},
        {"name": "Devbhumi Dwarka", "code": "GJ-DD", "lgd": "670"},
        {"name": "Gandhinagar", "code": "GJ-GA", "lgd": "446"},
        {"name": "Gir Somnath", "code": "GJ-GS", "lgd": "671"},
        {"name": "Jamnagar", "code": "GJ-JA", "lgd": "447"},
        {"name": "Junagadh", "code": "GJ-JU", "lgd": "448"},
        {"name": "Kheda", "code": "GJ-KH", "lgd": "449"},
        {"name": "Kutch", "code": "GJ-KU", "lgd": "450"},
        {"name": "Mahisagar", "code": "GJ-MH", "lgd": "672"},
        {"name": "Mehsana", "code": "GJ-MA", "lgd": "451"},
        {"name": "Morbi", "code": "GJ-MB", "lgd": "666"},
        {"name": "Narmada", "code": "GJ-NR", "lgd": "452"},
        {"name": "Navsari", "code": "GJ-NV", "lgd": "453"},
        {"name": "Panchmahals", "code": "GJ-PM", "lgd": "454"},
        {"name": "Patan", "code": "GJ-PA", "lgd": "455"},
        {"name": "Porbandar", "code": "GJ-PO", "lgd": "456"},
        {"name": "Rajkot", "code": "GJ-RA", "lgd": "457"},
        {"name": "Sabarkantha", "code": "GJ-SK", "lgd": "458"},
        {"name": "Surat", "code": "GJ-ST", "lgd": "459"},
        {"name": "Surendranagar", "code": "GJ-SN", "lgd": "460"},
        {"name": "Tapi", "code": "GJ-TA", "lgd": "610"},
        {"name": "Vadodara", "code": "GJ-VD", "lgd": "461"},
        {"name": "Valsad", "code": "GJ-VL", "lgd": "462"},
    ],
    "HARYANA": [
        {"name": "Ambala", "code": "HR-AM", "lgd": "57"},
        {"name": "Bhiwani", "code": "HR-BH", "lgd": "58"},
        {"name": "Charkhi Dadri", "code": "HR-CD", "lgd": "705"},
        {"name": "Faridabad", "code": "HR-FR", "lgd": "59"},
        {"name": "Fatehabad", "code": "HR-FT", "lgd": "60"},
        {"name": "Gurugram", "code": "HR-GG", "lgd": "61"},
        {"name": "Hisar", "code": "HR-HI", "lgd": "62"},
        {"name": "Jhajjar", "code": "HR-JH", "lgd": "63"},
        {"name": "Jind", "code": "HR-JI", "lgd": "64"},
        {"name": "Kaithal", "code": "HR-KT", "lgd": "65"},
        {"name": "Karnal", "code": "HR-KR", "lgd": "66"},
        {"name": "Kurukshetra", "code": "HR-KU", "lgd": "67"},
        {"name": "Mahendragarh", "code": "HR-MA", "lgd": "68"},
        {"name": "Nuh", "code": "HR-MW", "lgd": "604"},
        {"name": "Palwal", "code": "HR-PW", "lgd": "627"},
        {"name": "Panchkula", "code": "HR-PK", "lgd": "69"},
        {"name": "Panipat", "code": "HR-PP", "lgd": "70"},
        {"name": "Rewari", "code": "HR-RE", "lgd": "71"},
        {"name": "Rohtak", "code": "HR-RO", "lgd": "72"},
        {"name": "Sirsa", "code": "HR-SI", "lgd": "73"},
        {"name": "Sonipat", "code": "HR-SO", "lgd": "74"},
        {"name": "Yamunanagar", "code": "HR-YN", "lgd": "75"},
    ],
    "HIMACHAL PRADESH": [
        {"name": "Bilaspur", "code": "HP-BI", "lgd": "14"},
        {"name": "Chamba", "code": "HP-CH", "lgd": "15"},
        {"name": "Hamirpur", "code": "HP-HA", "lgd": "16"},
        {"name": "Kangra", "code": "HP-KA", "lgd": "17"},
        {"name": "Kinnaur", "code": "HP-KI", "lgd": "18"},
        {"name": "Kullu", "code": "HP-KU", "lgd": "19"},
        {"name": "Lahaul and Spiti", "code": "HP-LS", "lgd": "20"},
        {"name": "Mandi", "code": "HP-MA", "lgd": "21"},
        {"name": "Shimla", "code": "HP-SH", "lgd": "22"},
        {"name": "Sirmaur", "code": "HP-SI", "lgd": "23"},
        {"name": "Solan", "code": "HP-SO", "lgd": "24"},
        {"name": "Una", "code": "HP-UN", "lgd": "25"},
    ],
    "JHARKHAND": [
        {"name": "Bokaro", "code": "JH-BO", "lgd": "322"},
        {"name": "Chatra", "code": "JH-CH", "lgd": "323"},
        {"name": "Deoghar", "code": "JH-DE", "lgd": "324"},
        {"name": "Dhanbad", "code": "JH-DH", "lgd": "325"},
        {"name": "Dumka", "code": "JH-DU", "lgd": "326"},
        {"name": "East Singhbhum", "code": "JH-ES", "lgd": "327"},
        {"name": "Garhwa", "code": "JH-GA", "lgd": "328"},
        {"name": "Giridih", "code": "JH-GI", "lgd": "329"},
        {"name": "Godda", "code": "JH-GO", "lgd": "330"},
        {"name": "Gumla", "code": "JH-GU", "lgd": "331"},
        {"name": "Hazaribagh", "code": "JH-HA", "lgd": "332"},
        {"name": "Jamtara", "code": "JH-JA", "lgd": "573"},
        {"name": "Khunti", "code": "JH-KH", "lgd": "611"},
        {"name": "Koderma", "code": "JH-KO", "lgd": "333"},
        {"name": "Latehar", "code": "JH-LA", "lgd": "574"},
        {"name": "Lohardaga", "code": "JH-LO", "lgd": "334"},
        {"name": "Pakur", "code": "JH-PK", "lgd": "335"},
        {"name": "Palamu", "code": "JH-PL", "lgd": "336"},
        {"name": "Ramgarh", "code": "JH-RM", "lgd": "612"},
        {"name": "Ranchi", "code": "JH-RA", "lgd": "337"},
        {"name": "Sahibganj", "code": "JH-SA", "lgd": "338"},
        {"name": "Seraikela Kharsawan", "code": "JH-SK", "lgd": "575"},
        {"name": "Simdega", "code": "JH-SI", "lgd": "576"},
        {"name": "West Singhbhum", "code": "JH-WS", "lgd": "339"},
    ],
    "KARNATAKA": [
        {"name": "Bagalkote", "code": "KA-BK", "lgd": "524"},
        {"name": "Ballari", "code": "KA-BL", "lgd": "525"},
        {"name": "Belagavi", "code": "KA-BG", "lgd": "526"},
        {"name": "Bengaluru Rural", "code": "KA-BR", "lgd": "527"},
        {"name": "Bengaluru Urban", "code": "KA-BU", "lgd": "528"},
        {"name": "Bidar", "code": "KA-BD", "lgd": "529"},
        {"name": "Chamarajanagara", "code": "KA-CJ", "lgd": "530"},
        {"name": "Chikkaballapura", "code": "KA-CB", "lgd": "613"},
        {"name": "Chikkamagaluru", "code": "KA-CK", "lgd": "531"},
        {"name": "Chitradurga", "code": "KA-CT", "lgd": "532"},
        {"name": "Dakshina Kannada", "code": "KA-DK", "lgd": "533"},
        {"name": "Davanagere", "code": "KA-DA", "lgd": "534"},
        {"name": "Dharwad", "code": "KA-DH", "lgd": "535"},
        {"name": "Gadag", "code": "KA-GA", "lgd": "536"},
        {"name": "Hassan", "code": "KA-HS", "lgd": "537"},
        {"name": "Haveri", "code": "KA-HV", "lgd": "538"},
        {"name": "Kalaburagi", "code": "KA-GU", "lgd": "539"},
        {"name": "Kodagu", "code": "KA-KD", "lgd": "540"},
        {"name": "Kolar", "code": "KA-KL", "lgd": "541"},
        {"name": "Koppal", "code": "KA-KP", "lgd": "542"},
        {"name": "Mandya", "code": "KA-MA", "lgd": "543"},
        {"name": "Mysuru", "code": "KA-MY", "lgd": "546"},
        {"name": "Raichur", "code": "KA-RA", "lgd": "547"},
        {"name": "Ramanagara", "code": "KA-RM", "lgd": "614"},
        {"name": "Shivamogga", "code": "KA-SH", "lgd": "548"},
        {"name": "Tumakuru", "code": "KA-TU", "lgd": "549"},
        {"name": "Udupi", "code": "KA-UD", "lgd": "550"},
        {"name": "Uttara Kannada", "code": "KA-UK", "lgd": "551"},
        {"name": "Vijayanagara", "code": "KA-VN", "lgd": "742"},
        {"name": "Vijayapura", "code": "KA-BJ", "lgd": "552"},
        {"name": "Yadgir", "code": "KA-YG", "lgd": "636"},
    ],
    "KERALA": [
        {"name": "Alappuzha", "code": "KL-AL", "lgd": "554"},
        {"name": "Ernakulam", "code": "KL-ER", "lgd": "555"},
        {"name": "Idukki", "code": "KL-ID", "lgd": "556"},
        {"name": "Kannur", "code": "KL-KN", "lgd": "557"},
        {"name": "Kasaragod", "code": "KL-KS", "lgd": "558"},
        {"name": "Kollam", "code": "KL-KL", "lgd": "559"},
        {"name": "Kottayam", "code": "KL-KT", "lgd": "560"},
        {"name": "Kozhikode", "code": "KL-KZ", "lgd": "561"},
        {"name": "Malappuram", "code": "KL-MA", "lgd": "562"},
        {"name": "Palakkad", "code": "KL-PL", "lgd": "563"},
        {"name": "Pathanamthitta", "code": "KL-PT", "lgd": "564"},
        {"name": "Thiruvananthapuram", "code": "KL-TV", "lgd": "565"},
        {"name": "Thrissur", "code": "KL-TS", "lgd": "566"},
        {"name": "Wayanad", "code": "KL-WA", "lgd": "567"},
    ],
    "MADHYA PRADESH": [
        {"name": "Agar Malwa", "code": "MP-AG", "lgd": "665"},
        {"name": "Alirajpur", "code": "MP-AL", "lgd": "617"},
        {"name": "Anuppur", "code": "MP-AP", "lgd": "581"},
        {"name": "Ashoknagar", "code": "MP-AS", "lgd": "582"},
        {"name": "Balaghat", "code": "MP-BL", "lgd": "390"},
        {"name": "Barwani", "code": "MP-BR", "lgd": "391"},
        {"name": "Betul", "code": "MP-BE", "lgd": "392"},
        {"name": "Bhind", "code": "MP-BD", "lgd": "393"},
        {"name": "Bhopal", "code": "MP-BP", "lgd": "394"},
        {"name": "Burhanpur", "code": "MP-BU", "lgd": "583"},
        {"name": "Chhatarpur", "code": "MP-CT", "lgd": "395"},
        {"name": "Chhindwara", "code": "MP-CW", "lgd": "396"},
        {"name": "Damoh", "code": "MP-DM", "lgd": "397"},
        {"name": "Datia", "code": "MP-DT", "lgd": "398"},
        {"name": "Dewas", "code": "MP-DE", "lgd": "399"},
        {"name": "Dhar", "code": "MP-DH", "lgd": "400"},
        {"name": "Dindori", "code": "MP-DI", "lgd": "401"},
        {"name": "Guna", "code": "MP-GU", "lgd": "402"},
        {"name": "Gwalior", "code": "MP-GW", "lgd": "403"},
        {"name": "Harda", "code": "MP-HA", "lgd": "404"},
        {"name": "Narmadapuram", "code": "MP-HO", "lgd": "405"},
        {"name": "Indore", "code": "MP-IN", "lgd": "406"},
        {"name": "Jabalpur", "code": "MP-JA", "lgd": "407"},
        {"name": "Jhabua", "code": "MP-JH", "lgd": "408"},
        {"name": "Katni", "code": "MP-KA", "lgd": "409"},
        {"name": "Khandwa", "code": "MP-EN", "lgd": "410"},
        {"name": "Khargone", "code": "MP-WN", "lgd": "411"},
        {"name": "Maihar", "code": "MP-MR", "lgd": "766"},
        {"name": "Mandla", "code": "MP-ML", "lgd": "412"},
        {"name": "Mandsaur", "code": "MP-MS", "lgd": "413"},
        {"name": "Mauganj", "code": "MP-MG", "lgd": "767"},
        {"name": "Morena", "code": "MP-MO", "lgd": "414"},
        {"name": "Narsinghpur", "code": "MP-NA", "lgd": "415"},
        {"name": "Neemuch", "code": "MP-NE", "lgd": "416"},
        {"name": "Niwari", "code": "MP-NW", "lgd": "725"},
        {"name": "Pandhurna", "code": "MP-PD", "lgd": "768"},
        {"name": "Panna", "code": "MP-PA", "lgd": "417"},
        {"name": "Raisen", "code": "MP-RS", "lgd": "418"},
        {"name": "Rajgarh", "code": "MP-RG", "lgd": "419"},
        {"name": "Ratlam", "code": "MP-RL", "lgd": "420"},
        {"name": "Rewa", "code": "MP-RE", "lgd": "421"},
        {"name": "Sagar", "code": "MP-SG", "lgd": "422"},
        {"name": "Satna", "code": "MP-ST", "lgd": "423"},
        {"name": "Sehore", "code": "MP-SR", "lgd": "424"},
        {"name": "Seoni", "code": "MP-SO", "lgd": "425"},
        {"name": "Shahdol", "code": "MP-SH", "lgd": "426"},
        {"name": "Shajapur", "code": "MP-SJ", "lgd": "427"},
        {"name": "Sheopur", "code": "MP-SP", "lgd": "428"},
        {"name": "Shivpuri", "code": "MP-SV", "lgd": "429"},
        {"name": "Sidhi", "code": "MP-SI", "lgd": "430"},
        {"name": "Singrauli", "code": "MP-SN", "lgd": "618"},
        {"name": "Tikamgarh", "code": "MP-TI", "lgd": "431"},
        {"name": "Ujjain", "code": "MP-UJ", "lgd": "432"},
        {"name": "Umaria", "code": "MP-UM", "lgd": "433"},
        {"name": "Vidisha", "code": "MP-VI", "lgd": "434"},
    ],
    "MAHARASHTRA": [
        {"name": "Ahmednagar", "code": "MH-AH", "lgd": "464"},
        {"name": "Akola", "code": "MH-AK", "lgd": "465"},
        {"name": "Amravati", "code": "MH-AM", "lgd": "466"},
        {"name": "Chhatrapati Sambhajinagar", "code": "MH-AU", "lgd": "467"},
        {"name": "Beed", "code": "MH-BI", "lgd": "468"},
        {"name": "Bhandara", "code": "MH-BH", "lgd": "469"},
        {"name": "Buldhana", "code": "MH-BU", "lgd": "470"},
        {"name": "Chandrapur", "code": "MH-CH", "lgd": "471"},
        {"name": "Dhule", "code": "MH-DH", "lgd": "472"},
        {"name": "Gadchiroli", "code": "MH-GA", "lgd": "473"},
        {"name": "Gondia", "code": "MH-GO", "lgd": "474"},
        {"name": "Hingoli", "code": "MH-HI", "lgd": "475"},
        {"name": "Jalgaon", "code": "MH-JG", "lgd": "476"},
        {"name": "Jalna", "code": "MH-JN", "lgd": "477"},
        {"name": "Kolhapur", "code": "MH-KO", "lgd": "478"},
        {"name": "Latur", "code": "MH-LA", "lgd": "479"},
        {"name": "Mumbai City", "code": "MH-MC", "lgd": "480"},
        {"name": "Mumbai Suburban", "code": "MH-MU", "lgd": "481"},
        {"name": "Nagpur", "code": "MH-NG", "lgd": "482"},
        {"name": "Nanded", "code": "MH-ND", "lgd": "483"},
        {"name": "Nandurbar", "code": "MH-NB", "lgd": "484"},
        {"name": "Nashik", "code": "MH-NS", "lgd": "485"},
        {"name": "Dharashiv", "code": "MH-OS", "lgd": "486"},
        {"name": "Palghar", "code": "MH-PL", "lgd": "676"},
        {"name": "Parbhani", "code": "MH-PA", "lgd": "487"},
        {"name": "Pune", "code": "MH-PU", "lgd": "488"},
        {"name": "Raigad", "code": "MH-RG", "lgd": "489"},
        {"name": "Ratnagiri", "code": "MH-RT", "lgd": "490"},
        {"name": "Sangli", "code": "MH-SN", "lgd": "491"},
        {"name": "Satara", "code": "MH-ST", "lgd": "492"},
        {"name": "Sindhudurg", "code": "MH-SI", "lgd": "493"},
        {"name": "Solapur", "code": "MH-SO", "lgd": "494"},
        {"name": "Thane", "code": "MH-TH", "lgd": "495"},
        {"name": "Wardha", "code": "MH-WR", "lgd": "496"},
        {"name": "Washim", "code": "MH-WS", "lgd": "497"},
        {"name": "Yavatmal", "code": "MH-YA", "lgd": "498"},
    ],
    "MANIPUR": [
        {"name": "Bishnupur", "code": "MN-BI", "lgd": "252"},
        {"name": "Chandel", "code": "MN-CC", "lgd": "253"},
        {"name": "Churachandpur", "code": "MN-CC", "lgd": "254"},
        {"name": "Imphal East", "code": "MN-EI", "lgd": "255"},
        {"name": "Imphal West", "code": "MN-WI", "lgd": "256"},
        {"name": "Jiribam", "code": "MN-JB", "lgd": "691"},
        {"name": "Kakching", "code": "MN-KC", "lgd": "692"},
        {"name": "Kamjong", "code": "MN-KJ", "lgd": "693"},
        {"name": "Kangpokpi", "code": "MN-KP", "lgd": "694"},
        {"name": "Noney", "code": "MN-NN", "lgd": "695"},
        {"name": "Pherzawl", "code": "MN-PZ", "lgd": "696"},
        {"name": "Senapati", "code": "MN-SE", "lgd": "257"},
        {"name": "Tamenglong", "code": "MN-TA", "lgd": "258"},
        {"name": "Tengnoupal", "code": "MN-TN", "lgd": "697"},
        {"name": "Thoubal", "code": "MN-TH", "lgd": "259"},
        {"name": "Ukhrul", "code": "MN-UK", "lgd": "260"},
    ],
    "MEGHALAYA": [
        {"name": "Eastern West Khasi Hills", "code": "ML-EW", "lgd": "741"},
        {"name": "East Garo Hills", "code": "ML-EG", "lgd": "270"},
        {"name": "East Jaintia Hills", "code": "ML-EJ", "lgd": "659"},
        {"name": "East Khasi Hills", "code": "ML-EK", "lgd": "271"},
        {"name": "North Garo Hills", "code": "ML-NG", "lgd": "660"},
        {"name": "Ri Bhoi", "code": "ML-RB", "lgd": "272"},
        {"name": "South Garo Hills", "code": "ML-SG", "lgd": "273"},
        {"name": "South West Garo Hills", "code": "ML-SW", "lgd": "661"},
        {"name": "South West Khasi Hills", "code": "ML-SK", "lgd": "662"},
        {"name": "West Garo Hills", "code": "ML-WG", "lgd": "274"},
        {"name": "West Jaintia Hills", "code": "ML-WJ", "lgd": "663"},
        {"name": "West Khasi Hills", "code": "ML-WK", "lgd": "275"},
    ],
    "MIZORAM": [
        {"name": "Aizawl", "code": "MZ-AI", "lgd": "261"},
        {"name": "Champhai", "code": "MZ-CH", "lgd": "262"},
        {"name": "Hnahthial", "code": "MZ-HN", "lgd": "729"},
        {"name": "Khawzawl", "code": "MZ-KZ", "lgd": "730"},
        {"name": "Kolasib", "code": "MZ-KO", "lgd": "263"},
        {"name": "Lawngtlai", "code": "MZ-LA", "lgd": "264"},
        {"name": "Lunglei", "code": "MZ-LU", "lgd": "265"},
        {"name": "Mamit", "code": "MZ-MA", "lgd": "266"},
        {"name": "Saitual", "code": "MZ-ST", "lgd": "731"},
        {"name": "Serchhip", "code": "MZ-SE", "lgd": "267"},
        {"name": "Siaha", "code": "MZ-SI", "lgd": "268"},
    ],
    "NAGALAND": [
        {"name": "Chumoukedima", "code": "NL-CK", "lgd": "757"},
        {"name": "Dimapur", "code": "NL-DI", "lgd": "245"},
        {"name": "Kiphire", "code": "NL-KI", "lgd": "584"},
        {"name": "Kohima", "code": "NL-KO", "lgd": "246"},
        {"name": "Longleng", "code": "NL-LO", "lgd": "585"},
        {"name": "Mokokchung", "code": "NL-MO", "lgd": "247"},
        {"name": "Mon", "code": "NL-MN", "lgd": "248"},
        {"name": "Niuland", "code": "NL-NU", "lgd": "740"},
        {"name": "Noklak", "code": "NL-NK", "lgd": "723"},
        {"name": "Peren", "code": "NL-PE", "lgd": "586"},
        {"name": "Phek", "code": "NL-PH", "lgd": "249"},
        {"name": "Shamator", "code": "NL-SM", "lgd": "763"},
        {"name": "Tseminyu", "code": "NL-TS", "lgd": "739"},
        {"name": "Tuensang", "code": "NL-TU", "lgd": "250"},
        {"name": "Wokha", "code": "NL-WO", "lgd": "251"},
        {"name": "Zunheboto", "code": "NL-ZU", "lgd": "269"},
    ],
    "ODISHA": [
        {"name": "Angul", "code": "OD-AN", "lgd": "340"},
        {"name": "Balangir", "code": "OD-BL", "lgd": "341"},
        {"name": "Balasore", "code": "OD-BS", "lgd": "342"},
        {"name": "Bargarh", "code": "OD-BG", "lgd": "343"},
        {"name": "Bhadrak", "code": "OD-BH", "lgd": "344"},
        {"name": "Boudh", "code": "OD-BO", "lgd": "345"},
        {"name": "Cuttack", "code": "OD-CU", "lgd": "346"},
        {"name": "Deogarh", "code": "OD-DE", "lgd": "347"},
        {"name": "Dhenkanal", "code": "OD-DH", "lgd": "348"},
        {"name": "Gajapati", "code": "OD-GA", "lgd": "349"},
        {"name": "Ganjam", "code": "OD-GM", "lgd": "350"},
        {"name": "Jagatsinghpur", "code": "OD-JS", "lgd": "351"},
        {"name": "Jajpur", "code": "OD-JP", "lgd": "352"},
        {"name": "Jharsuguda", "code": "OD-JH", "lgd": "353"},
        {"name": "Kalahandi", "code": "OD-KL", "lgd": "354"},
        {"name": "Kandhamal", "code": "OD-KD", "lgd": "355"},
        {"name": "Kendrapara", "code": "OD-KR", "lgd": "356"},
        {"name": "Kendujhar", "code": "OD-KJ", "lgd": "357"},
        {"name": "Khordha", "code": "OD-KH", "lgd": "358"},
        {"name": "Koraput", "code": "OD-KP", "lgd": "359"},
        {"name": "Malkangiri", "code": "OD-ML", "lgd": "360"},
        {"name": "Mayurbhanj", "code": "OD-MY", "lgd": "361"},
        {"name": "Nabarangpur", "code": "OD-NB", "lgd": "362"},
        {"name": "Nayagarh", "code": "OD-NY", "lgd": "363"},
        {"name": "Nuapada", "code": "OD-NU", "lgd": "364"},
        {"name": "Puri", "code": "OD-PU", "lgd": "365"},
        {"name": "Rayagada", "code": "OD-RA", "lgd": "366"},
        {"name": "Sambalpur", "code": "OD-SA", "lgd": "367"},
        {"name": "Subarnapur", "code": "OD-SO", "lgd": "368"},
        {"name": "Sundargarh", "code": "OD-SU", "lgd": "369"},
    ],
    "PUNJAB": [
        {"name": "Amritsar", "code": "PB-AM", "lgd": "26"},
        {"name": "Barnala", "code": "PB-BN", "lgd": "605"},
        {"name": "Bathinda", "code": "PB-BA", "lgd": "27"},
        {"name": "Faridkot", "code": "PB-FD", "lgd": "28"},
        {"name": "Fatehgarh Sahib", "code": "PB-FT", "lgd": "29"},
        {"name": "Fazilka", "code": "PB-FZ", "lgd": "655"},
        {"name": "Ferozepur", "code": "PB-FR", "lgd": "30"},
        {"name": "Gurdaspur", "code": "PB-GU", "lgd": "31"},
        {"name": "Hoshiarpur", "code": "PB-HO", "lgd": "32"},
        {"name": "Jalandhar", "code": "PB-JA", "lgd": "33"},
        {"name": "Kapurthala", "code": "PB-KA", "lgd": "34"},
        {"name": "Ludhiana", "code": "PB-LU", "lgd": "35"},
        {"name": "Malerkotla", "code": "PB-ML", "lgd": "738"},
        {"name": "Mansa", "code": "PB-MA", "lgd": "36"},
        {"name": "Moga", "code": "PB-MO", "lgd": "37"},
        {"name": "Muktsar", "code": "PB-MU", "lgd": "38"},
        {"name": "Pathankot", "code": "PB-PK", "lgd": "656"},
        {"name": "Patiala", "code": "PB-PA", "lgd": "39"},
        {"name": "Rupnagar", "code": "PB-RU", "lgd": "40"},
        {"name": "Sahibzada Ajit Singh Nagar", "code": "PB-SA", "lgd": "606"},
        {"name": "Sangrur", "code": "PB-SN", "lgd": "41"},
        {"name": "Shahid Bhagat Singh Nagar", "code": "PB-NB", "lgd": "42"},
        {"name": "Tarn Taran", "code": "PB-TT", "lgd": "587"},
    ],
    "RAJASTHAN": [
        {"name": "Ajmer", "code": "RJ-AJ", "lgd": "84"},
        {"name": "Alwar", "code": "RJ-AL", "lgd": "85"},
        {"name": "Anupgarh", "code": "RJ-AN", "lgd": "747"},
        {"name": "Balotra", "code": "RJ-BL", "lgd": "748"},
        {"name": "Banswara", "code": "RJ-BN", "lgd": "86"},
        {"name": "Baran", "code": "RJ-BR", "lgd": "87"},
        {"name": "Barmer", "code": "RJ-BM", "lgd": "88"},
        {"name": "Beawar", "code": "RJ-BW", "lgd": "749"},
        {"name": "Bharatpur", "code": "RJ-BH", "lgd": "89"},
        {"name": "Bhilwara", "code": "RJ-BW", "lgd": "90"},
        {"name": "Bikaner", "code": "RJ-BI", "lgd": "91"},
        {"name": "Bundi", "code": "RJ-BU", "lgd": "92"},
        {"name": "Chittorgarh", "code": "RJ-CT", "lgd": "93"},
        {"name": "Churu", "code": "RJ-CR", "lgd": "94"},
        {"name": "Dausa", "code": "RJ-DA", "lgd": "95"},
        {"name": "Deeg", "code": "RJ-DG", "lgd": "750"},
        {"name": "Dholpur", "code": "RJ-DH", "lgd": "96"},
        {"name": "Didwana-Kuchaman", "code": "RJ-DK", "lgd": "751"},
        {"name": "Dudu", "code": "RJ-DD", "lgd": "752"},
        {"name": "Dungarpur", "code": "RJ-DU", "lgd": "97"},
        {"name": "Gangapur City", "code": "RJ-GC", "lgd": "753"},
        {"name": "Hanumangarh", "code": "RJ-HA", "lgd": "98"},
        {"name": "Jaipur", "code": "RJ-JP", "lgd": "99"},
        {"name": "Jaipur Rural", "code": "RJ-JR", "lgd": "754"},
        {"name": "Jaisalmer", "code": "RJ-JL", "lgd": "100"},
        {"name": "Jalore", "code": "RJ-JA", "lgd": "101"},
        {"name": "Jhalawar", "code": "RJ-JW", "lgd": "102"},
        {"name": "Jhunjhunu", "code": "RJ-JJ", "lgd": "103"},
        {"name": "Jodhpur", "code": "RJ-JO", "lgd": "104"},
        {"name": "Jodhpur Rural", "code": "RJ-JDR", "lgd": "755"},
        {"name": "Karauli", "code": "RJ-KA", "lgd": "105"},
        {"name": "Kekri", "code": "RJ-KK", "lgd": "756"},
        {"name": "Khairthal-Tijara", "code": "RJ-KT", "lgd": "757"},
        {"name": "Kota", "code": "RJ-KO", "lgd": "106"},
        {"name": "Kotputli-Behror", "code": "RJ-KB", "lgd": "758"},
        {"name": "Nagaur", "code": "RJ-NA", "lgd": "107"},
        {"name": "Neem Ka Thana", "code": "RJ-NT", "lgd": "759"},
        {"name": "Pali", "code": "RJ-PA", "lgd": "108"},
        {"name": "Phalodi", "code": "RJ-PH", "lgd": "760"},
        {"name": "Pratapgarh", "code": "RJ-PR", "lgd": "634"},
        {"name": "Rajsamand", "code": "RJ-RA", "lgd": "109"},
        {"name": "Salumber", "code": "RJ-SL", "lgd": "761"},
        {"name": "Sanchore", "code": "RJ-SC", "lgd": "762"},
        {"name": "Sawai Madhopur", "code": "RJ-SM", "lgd": "110"},
        {"name": "Shahpura", "code": "RJ-SH", "lgd": "763"},
        {"name": "Sikar", "code": "RJ-SK", "lgd": "111"},
        {"name": "Sirohi", "code": "RJ-SR", "lgd": "112"},
        {"name": "Sri Ganganagar", "code": "RJ-GA", "lgd": "113"},
        {"name": "Tonk", "code": "RJ-TO", "lgd": "114"},
        {"name": "Udaipur", "code": "RJ-UD", "lgd": "115"},
    ],
    "SIKKIM": [
        {"name": "Gangtok", "code": "SK-EG", "lgd": "225"},
        {"name": "Gyalshing", "code": "SK-WG", "lgd": "226"},
        {"name": "Mangan", "code": "SK-NG", "lgd": "227"},
        {"name": "Namchi", "code": "SK-SG", "lgd": "228"},
        {"name": "Pakyong", "code": "SK-PY", "lgd": "735"},
        {"name": "Soreng", "code": "SK-SR", "lgd": "736"},
    ],
    "TAMIL NADU": [
        {"name": "Ariyalur", "code": "TN-AR", "lgd": "619"},
        {"name": "Chengalpattu", "code": "TN-CG", "lgd": "732"},
        {"name": "Chennai", "code": "TN-CH", "lgd": "568"},
        {"name": "Coimbatore", "code": "TN-CO", "lgd": "569"},
        {"name": "Cuddalore", "code": "TN-CU", "lgd": "570"},
        {"name": "Dharmapuri", "code": "TN-DH", "lgd": "571"},
        {"name": "Dindigul", "code": "TN-DI", "lgd": "588"},
        {"name": "Erode", "code": "TN-ER", "lgd": "589"},
        {"name": "Kallakurichi", "code": "TN-KL", "lgd": "734"},
        {"name": "Kanchipuram", "code": "TN-KC", "lgd": "590"},
        {"name": "Kanyakumari", "code": "TN-KK", "lgd": "591"},
        {"name": "Karur", "code": "TN-KR", "lgd": "592"},
        {"name": "Krishnagiri", "code": "TN-KG", "lgd": "593"},
        {"name": "Madurai", "code": "TN-MA", "lgd": "594"},
        {"name": "Mayiladuthurai", "code": "TN-MY", "lgd": "737"},
        {"name": "Nagapattinam", "code": "TN-NG", "lgd": "595"},
        {"name": "Namakkal", "code": "TN-NM", "lgd": "596"},
        {"name": "Nilgiris", "code": "TN-NI", "lgd": "597"},
        {"name": "Perambalur", "code": "TN-PE", "lgd": "598"},
        {"name": "Pudukkottai", "code": "TN-PU", "lgd": "599"},
        {"name": "Ramanathapuram", "code": "TN-RA", "lgd": "600"},
        {"name": "Ranipet", "code": "TN-RN", "lgd": "735"},
        {"name": "Salem", "code": "TN-SA", "lgd": "601"},
        {"name": "Sivaganga", "code": "TN-SI", "lgd": "602"},
        {"name": "Tenkasi", "code": "TN-TS", "lgd": "736"},
        {"name": "Thanjavur", "code": "TN-TJ", "lgd": "609"},
        {"name": "Theni", "code": "TN-TH", "lgd": "615"},
        {"name": "Thoothukudi", "code": "TN-TK", "lgd": "616"},
        {"name": "Tiruchirappalli", "code": "TN-TC", "lgd": "620"},
        {"name": "Tirunelveli", "code": "TN-TI", "lgd": "621"},
        {"name": "Tirupathur", "code": "TN-TP", "lgd": "738"},
        {"name": "Tiruppur", "code": "TN-TU", "lgd": "633"},
        {"name": "Tiruvallur", "code": "TN-TL", "lgd": "622"},
        {"name": "Tiruvannamalai", "code": "TN-TV", "lgd": "623"},
        {"name": "Tiruvarur", "code": "TN-TR", "lgd": "624"},
        {"name": "Vellore", "code": "TN-VE", "lgd": "625"},
        {"name": "Viluppuram", "code": "TN-VL", "lgd": "626"},
        {"name": "Virudhunagar", "code": "TN-VR", "lgd": "628"},
    ],
    "TELANGANA": [
        {"name": "Adilabad", "code": "TG-AD", "lgd": "501"},
        {"name": "Bhadradri Kothagudem", "code": "TG-BK", "lgd": "680"},
        {"name": "Hanamkonda", "code": "TG-HN", "lgd": "681"},
        {"name": "Hyderabad", "code": "TG-HY", "lgd": "507"},
        {"name": "Jagtial", "code": "TG-JG", "lgd": "682"},
        {"name": "Jangaon", "code": "TG-JN", "lgd": "683"},
        {"name": "Jayashankar Bhupalpally", "code": "TG-JB", "lgd": "684"},
        {"name": "Jogulamba Gadwal", "code": "TG-JG", "lgd": "685"},
        {"name": "Kamareddy", "code": "TG-KM", "lgd": "686"},
        {"name": "Karimnagar", "code": "TG-KA", "lgd": "508"},
        {"name": "Khammam", "code": "TG-KH", "lgd": "509"},
        {"name": "Kumuram Bheem Asifabad", "code": "TG-KB", "lgd": "687"},
        {"name": "Mahabubabad", "code": "TG-MH", "lgd": "688"},
        {"name": "Mahabubnagar", "code": "TG-MB", "lgd": "512"},
        {"name": "Mancherial", "code": "TG-MC", "lgd": "689"},
        {"name": "Medak", "code": "TG-MD", "lgd": "513"},
        {"name": "Medchal-Malkajgiri", "code": "TG-MM", "lgd": "690"},
        {"name": "Mulugu", "code": "TG-ML", "lgd": "730"},
        {"name": "Nagarkurnool", "code": "TG-NG", "lgd": "691"},
        {"name": "Nalgonda", "code": "TG-NL", "lgd": "514"},
        {"name": "Narayanpet", "code": "TG-NP", "lgd": "731"},
        {"name": "Nirmal", "code": "TG-NR", "lgd": "692"},
        {"name": "Nizamabad", "code": "TG-NZ", "lgd": "516"},
        {"name": "Peddapalli", "code": "TG-PD", "lgd": "693"},
        {"name": "Rajanna Sircilla", "code": "TG-RS", "lgd": "694"},
        {"name": "Ranga Reddy", "code": "TG-RR", "lgd": "518"},
        {"name": "Sangareddy", "code": "TG-SR", "lgd": "695"},
        {"name": "Siddipet", "code": "TG-SD", "lgd": "696"},
        {"name": "Suryapet", "code": "TG-SP", "lgd": "697"},
        {"name": "Vikarabad", "code": "TG-VK", "lgd": "698"},
        {"name": "Wanaparthy", "code": "TG-WN", "lgd": "699"},
        {"name": "Warangal", "code": "TG-WL", "lgd": "522"},
        {"name": "Yadadri Bhuvanagiri", "code": "TG-YB", "lgd": "700"},
    ],
    "TRIPURA": [
        {"name": "Dhalai", "code": "TR-DH", "lgd": "276"},
        {"name": "Gomati", "code": "TR-GM", "lgd": "664"},
        {"name": "Khowai", "code": "TR-KH", "lgd": "665"},
        {"name": "North Tripura", "code": "TR-NT", "lgd": "277"},
        {"name": "Sepahijala", "code": "TR-SP", "lgd": "666"},
        {"name": "South Tripura", "code": "TR-ST", "lgd": "278"},
        {"name": "Unakoti", "code": "TR-UK", "lgd": "667"},
        {"name": "West Tripura", "code": "TR-WT", "lgd": "279"},
    ],
    "UTTAR PRADESH": [
        {"name": "Agra", "code": "UP-AG", "lgd": "116"},
        {"name": "Aligarh", "code": "UP-AL", "lgd": "117"},
        {"name": "Ambedkar Nagar", "code": "UP-AN", "lgd": "118"},
        {"name": "Amethi", "code": "UP-AM", "lgd": "640"},
        {"name": "Amroha", "code": "UP-JP", "lgd": "119"},
        {"name": "Auraiya", "code": "UP-AU", "lgd": "120"},
        {"name": "Ayodhya", "code": "UP-FA", "lgd": "121"},
        {"name": "Azamgarh", "code": "UP-AZ", "lgd": "122"},
        {"name": "Baghpat", "code": "UP-BG", "lgd": "123"},
        {"name": "Bahraich", "code": "UP-BH", "lgd": "124"},
        {"name": "Ballia", "code": "UP-BL", "lgd": "125"},
        {"name": "Balrampur", "code": "UP-BP", "lgd": "126"},
        {"name": "Banda", "code": "UP-BN", "lgd": "127"},
        {"name": "Barabanki", "code": "UP-BB", "lgd": "128"},
        {"name": "Bareilly", "code": "UP-BR", "lgd": "129"},
        {"name": "Basti", "code": "UP-BS", "lgd": "130"},
        {"name": "Bhadohi", "code": "UP-SR", "lgd": "131"},
        {"name": "Bijnor", "code": "UP-BI", "lgd": "132"},
        {"name": "Budaun", "code": "UP-BD", "lgd": "133"},
        {"name": "Bulandshahr", "code": "UP-BU", "lgd": "134"},
        {"name": "Chandauli", "code": "UP-CD", "lgd": "135"},
        {"name": "Chitrakoot", "code": "UP-CT", "lgd": "136"},
        {"name": "Deoria", "code": "UP-DE", "lgd": "137"},
        {"name": "Etah", "code": "UP-ET", "lgd": "138"},
        {"name": "Etawah", "code": "UP-EW", "lgd": "139"},
        {"name": "Farrukhabad", "code": "UP-FR", "lgd": "140"},
        {"name": "Fatehpur", "code": "UP-FT", "lgd": "141"},
        {"name": "Firozabad", "code": "UP-FI", "lgd": "142"},
        {"name": "Gautam Buddha Nagar", "code": "UP-GB", "lgd": "143"},
        {"name": "Ghaziabad", "code": "UP-GZ", "lgd": "144"},
        {"name": "Ghazipur", "code": "UP-GP", "lgd": "145"},
        {"name": "Gonda", "code": "UP-GN", "lgd": "146"},
        {"name": "Gorakhpur", "code": "UP-GR", "lgd": "147"},
        {"name": "Hamirpur", "code": "UP-HM", "lgd": "148"},
        {"name": "Hapur", "code": "UP-HP", "lgd": "641"},
        {"name": "Hardoi", "code": "UP-HR", "lgd": "149"},
        {"name": "Hathras", "code": "UP-HT", "lgd": "150"},
        {"name": "Jalaun", "code": "UP-JL", "lgd": "151"},
        {"name": "Jaunpur", "code": "UP-JU", "lgd": "152"},
        {"name": "Jhansi", "code": "UP-JH", "lgd": "153"},
        {"name": "Kannauj", "code": "UP-KJ", "lgd": "154"},
        {"name": "Kanpur Dehat", "code": "UP-KD", "lgd": "155"},
        {"name": "Kanpur Nagar", "code": "UP-KN", "lgd": "156"},
        {"name": "Kasganj", "code": "UP-KS", "lgd": "632"},
        {"name": "Kaushambi", "code": "UP-KS", "lgd": "157"},
        {"name": "Kushinagar", "code": "UP-KU", "lgd": "158"},
        {"name": "Lakhimpur Kheri", "code": "UP-LK", "lgd": "159"},
        {"name": "Lalitpur", "code": "UP-LA", "lgd": "160"},
        {"name": "Lucknow", "code": "UP-LU", "lgd": "161"},
        {"name": "Maharajganj", "code": "UP-MG", "lgd": "162"},
        {"name": "Mahoba", "code": "UP-MH", "lgd": "163"},
        {"name": "Mainpuri", "code": "UP-MP", "lgd": "164"},
        {"name": "Mathura", "code": "UP-MT", "lgd": "165"},
        {"name": "Mau", "code": "UP-MB", "lgd": "166"},
        {"name": "Meerut", "code": "UP-ME", "lgd": "167"},
        {"name": "Mirzapur", "code": "UP-MI", "lgd": "168"},
        {"name": "Moradabad", "code": "UP-MO", "lgd": "169"},
        {"name": "Muzaffarnagar", "code": "UP-MU", "lgd": "170"},
        {"name": "Pilibhit", "code": "UP-PI", "lgd": "171"},
        {"name": "Pratapgarh", "code": "UP-PR", "lgd": "172"},
        {"name": "Prayagraj", "code": "UP-AL", "lgd": "173"},
        {"name": "Raebareli", "code": "UP-RB", "lgd": "174"},
        {"name": "Rampur", "code": "UP-RA", "lgd": "175"},
        {"name": "Saharanpur", "code": "UP-SA", "lgd": "176"},
        {"name": "Sambhal", "code": "UP-SM", "lgd": "642"},
        {"name": "Sant Kabir Nagar", "code": "UP-SK", "lgd": "177"},
        {"name": "Shahjahanpur", "code": "UP-SJ", "lgd": "178"},
        {"name": "Shamli", "code": "UP-SH", "lgd": "643"},
        {"name": "Shravasti", "code": "UP-SV", "lgd": "179"},
        {"name": "Siddharthnagar", "code": "UP-SN", "lgd": "180"},
        {"name": "Sitapur", "code": "UP-SI", "lgd": "181"},
        {"name": "Sonbhadra", "code": "UP-SO", "lgd": "182"},
        {"name": "Sultanpur", "code": "UP-SU", "lgd": "183"},
        {"name": "Unnao", "code": "UP-UN", "lgd": "184"},
        {"name": "Varanasi", "code": "UP-VA", "lgd": "185"},
    ],
    "UTTARAKHAND": [
        {"name": "Almora", "code": "UK-AL", "lgd": "43"},
        {"name": "Bageshwar", "code": "UK-BA", "lgd": "44"},
        {"name": "Chamoli", "code": "UK-CL", "lgd": "45"},
        {"name": "Champawat", "code": "UK-CP", "lgd": "46"},
        {"name": "Dehradun", "code": "UK-DD", "lgd": "47"},
        {"name": "Haridwar", "code": "UK-HA", "lgd": "48"},
        {"name": "Nainital", "code": "UK-NA", "lgd": "49"},
        {"name": "Pauri Garhwal", "code": "UK-PG", "lgd": "50"},
        {"name": "Pithoragarh", "code": "UK-PI", "lgd": "51"},
        {"name": "Rudraprayag", "code": "UK-RP", "lgd": "52"},
        {"name": "Tehri Garhwal", "code": "UK-TG", "lgd": "53"},
        {"name": "Udham Singh Nagar", "code": "UK-US", "lgd": "54"},
        {"name": "Uttarkashi", "code": "UK-UT", "lgd": "55"},
    ],
    "WEST BENGAL": [
        {"name": "Alipurduar", "code": "WB-AP", "lgd": "664"},
        {"name": "Bankura", "code": "WB-BN", "lgd": "303"},
        {"name": "Birbhum", "code": "WB-BR", "lgd": "304"},
        {"name": "Cooch Behar", "code": "WB-CB", "lgd": "305"},
        {"name": "Dakshin Dinajpur", "code": "WB-DD", "lgd": "306"},
        {"name": "Darjeeling", "code": "WB-DA", "lgd": "307"},
        {"name": "Hooghly", "code": "WB-HO", "lgd": "308"},
        {"name": "Howrah", "code": "WB-HR", "lgd": "309"},
        {"name": "Jalpaiguri", "code": "WB-JA", "lgd": "310"},
        {"name": "Jhargram", "code": "WB-JH", "lgd": "703"},
        {"name": "Kalimpong", "code": "WB-KL", "lgd": "704"},
        {"name": "Kolkata", "code": "WB-KO", "lgd": "311"},
        {"name": "Malda", "code": "WB-MA", "lgd": "312"},
        {"name": "Murshidabad", "code": "WB-MU", "lgd": "313"},
        {"name": "Nadia", "code": "WB-NA", "lgd": "314"},
        {"name": "North 24 Parganas", "code": "WB-PN", "lgd": "315"},
        {"name": "Paschim Bardhaman", "code": "WB-PB", "lgd": "705"},
        {"name": "Paschim Medinipur", "code": "WB-PM", "lgd": "316"},
        {"name": "Purba Bardhaman", "code": "WB-PR", "lgd": "706"},
        {"name": "Purba Medinipur", "code": "WB-PE", "lgd": "317"},
        {"name": "Purulia", "code": "WB-PU", "lgd": "318"},
        {"name": "South 24 Parganas", "code": "WB-PS", "lgd": "319"},
        {"name": "Uttar Dinajpur", "code": "WB-UD", "lgd": "320"},
    ],
    "ANDAMAN AND NICOBAR ISLANDS": [
        {"name": "Nicobars", "code": "AN-NI", "lgd": "600"},
        {"name": "North and Middle Andaman", "code": "AN-NM", "lgd": "632"},
        {"name": "South Andaman", "code": "AN-SA", "lgd": "601"},
    ],
    "CHANDIGARH": [
        {"name": "Chandigarh", "code": "CH-CH", "lgd": "56"},
    ],
    "DADRA AND NAGAR HAVELI AND DAMAN AND DIU": [
        {"name": "Dadra and Nagar Haveli", "code": "DD-DN", "lgd": "463"},
        {"name": "Daman", "code": "DD-DA", "lgd": "464"},
        {"name": "Diu", "code": "DD-DI", "lgd": "465"},
    ],
    "DELHI": [
        {"name": "Central Delhi", "code": "DL-CD", "lgd": "76"},
        {"name": "East Delhi", "code": "DL-ED", "lgd": "77"},
        {"name": "New Delhi", "code": "DL-ND", "lgd": "78"},
        {"name": "North Delhi", "code": "DL-NO", "lgd": "79"},
        {"name": "North East Delhi", "code": "DL-NE", "lgd": "80"},
        {"name": "North West Delhi", "code": "DL-NW", "lgd": "81"},
        {"name": "Shahdara", "code": "DL-SD", "lgd": "657"},
        {"name": "South Delhi", "code": "DL-SD", "lgd": "82"},
        {"name": "South East Delhi", "code": "DL-SE", "lgd": "658"},
        {"name": "South West Delhi", "code": "DL-SW", "lgd": "83"},
        {"name": "West Delhi", "code": "DL-WD", "lgd": "84"},
    ],
    "JAMMU AND KASHMIR": [
        {"name": "Anantnag", "code": "JK-AN", "lgd": "1"},
        {"name": "Bandipora", "code": "JK-BP", "lgd": "629"},
        {"name": "Baramulla", "code": "JK-BR", "lgd": "2"},
        {"name": "Budgam", "code": "JK-BD", "lgd": "3"},
        {"name": "Doda", "code": "JK-DO", "lgd": "4"},
        {"name": "Ganderbal", "code": "JK-GB", "lgd": "630"},
        {"name": "Jammu", "code": "JK-JA", "lgd": "5"},
        {"name": "Kathua", "code": "JK-KT", "lgd": "6"},
        {"name": "Kishtwar", "code": "JK-KW", "lgd": "631"},
        {"name": "Kulgam", "code": "JK-KG", "lgd": "632"},
        {"name": "Kupwara", "code": "JK-KU", "lgd": "7"},
        {"name": "Poonch", "code": "JK-PO", "lgd": "8"},
        {"name": "Pulwama", "code": "JK-PU", "lgd": "9"},
        {"name": "Rajouri", "code": "JK-RA", "lgd": "10"},
        {"name": "Ramban", "code": "JK-RB", "lgd": "633"},
        {"name": "Reasi", "code": "JK-RS", "lgd": "634"},
        {"name": "Samba", "code": "JK-SB", "lgd": "635"},
        {"name": "Shopian", "code": "JK-SH", "lgd": "636"},
        {"name": "Srinagar", "code": "JK-SR", "lgd": "11"},
        {"name": "Udhampur", "code": "JK-UD", "lgd": "12"},
    ],
    "LADAKH": [
        {"name": "Kargil", "code": "LA-KR", "lgd": "13"},
        {"name": "Leh", "code": "LA-LE", "lgd": "14"},
    ],
    "LAKSHADWEEP": [
        {"name": "Lakshadweep", "code": "LD-LD", "lgd": "553"},
    ],
    "PUDUCHERRY": [
        {"name": "Karaikal", "code": "PY-KA", "lgd": "598"},
        {"name": "Mahe", "code": "PY-MA", "lgd": "599"},
        {"name": "Puducherry", "code": "PY-PO", "lgd": "600"},
        {"name": "Yanam", "code": "PY-YA", "lgd": "601"},
    ],
}

def export_district_master_excel(output_path: Path):
    """Exports data/processed/INDIA_DISTRICT_MASTER.xlsx."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "District Master"

    headers = ["State Order", "State/UT", "State Code", "Type", "District", "District Code", "LGD Code", "Source", "Current/Active Status"]
    ws.append(headers)

    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="1F497D", end_color="1F497D", fill_type="solid")
    for c_idx in range(1, len(headers) + 1):
        cell = ws.cell(row=1, column=c_idx)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center")

    total_districts = 0
    for order, state_name, state_type, state_code, sheet_name in OFFICIAL_STATES:
        dists = LGD_DISTRICT_MASTER.get(state_name.upper(), [])
        for d in dists:
            total_districts += 1
            ws.append([
                order,
                state_name,
                state_code,
                state_type,
                d["name"],
                d["code"],
                d["lgd"],
                "Local Government Directory (LGD) / GoI Master",
                "ACTIVE"
            ])

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions

    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(output_path)
    return total_districts
